schedules:
- cron: "0 10,11,12,13 * * THU"
  displayName: every thursdays
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


