schedules:
- cron: "55 8 * * FRI"
  displayName: every Fridays every 5 mins
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


