schedules:
- cron: "50 5 * * *"
  always: true
  displayName: Running on UTC time
  branches:
    include:
    - master


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


